import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/page'
import Footer from '@/components/footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Chuma Wakaba's Portfolio",
  description: "Generated by create next app, Chuma Wakaba's personal portfolio",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='grid grid-rows-layout h-screen min-w-full'>
          <Header/>
          <main>{children}</main>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
